# Generated by Django 4.2 on 2023-04-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[("1", "EASY"), ("2", "MEDIUM"), ("3", "HARD")],
                default="1",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="level",
            field=models.CharField(
                choices=[("1", "EASY"), ("2", "MEDIUM"), ("3", "HARD")],
                default="1",
                max_length=2,
            ),
        ),
    ]
