# Generated by Django 4.2 on 2023-04-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_question_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="output",
            field=models.TextField(blank=True),
        ),
    ]
