# Generated by Django 4.2 on 2023-04-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_testcase_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
